### PR TITLE
feat: basic browser notification service

### PR DESCRIPTION
**Pull request by datatypevoid**
I see you beat me to the punch with commit e99cf12, but I thought I'd go ahead and offer up this PR anyway. I implemented notification support basically the same as you, but all of the notification logic is stored in a separate file, leading to cleaner code and easier reuse. Take it or leave it, but thanks for the site either way!

### CODE REVIEW

**Comment by TheAlexLichter** [comment]
I think that the PR really adds value, because of the reusability of the code, avoiding an ("expensive") watcher and cleaning up other parts in general. Thanks a lot for that!

**Comment by TheAlexLichter** [comment]
Still, the problem is that the first API call will be reported as desktop notification too, which (IMO) isn't a good practice, because the user will see that status likely on the page itself. Anyway, I'll merge and change that behavior ☺️

**Comment by TheAlexLichter** [comment]
Oh, and thanks for the subtle style hint :P I just setup JS standard style for the whole project 😄

**Comment by datatypevoid** [comment]
Glad it was of some use. Thanks again for the site, super helpful in these early days of Albion's release, heh. Good call on the first API call being reported as a desktop notification, was late and things were starting to get fuzzy.

Also, Vue is awesome, I haven't got my hands dirty with it until now, but I really like the simplicity of it, coming from using Angular for the past few years.

**Comment by TheAlexLichter** [comment]
Also, there was an [issue](https://github.com/manniL/albionstatus-website/issues/8) with Safari and notifications, but it's gone now

Yeah, vue is really awesome! I enjoy that framework a lot

**Pull request merged**
